name: null

channels:
  - defaults

dependencies:
  - jupyterlab=1.2
  - nodejs=10.13
  - pip=19.3
  - pip:
    - jupyterlab-nvdashboard==0.1.*  # server-side component; client-side component installed in postBuild
  - python=3.7
  
