name: null

channels:
  - intel
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - cudatoolkit
  - gh
  - git
  - holoviews
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - matplotlib
  - panel
  - pandas
  - pip
  - pip:
    - -r file:requirements.txt
  - python
  - pyviz_comms
  - xeus-python  
